language: objective-c

rvm: 1.9.3

script:
  - xctool -workspace MyHoard.xcworkspace -scheme MyHoard -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace MyHoard.xcworkspace -scheme MyHoard -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -freshSimulator -freshInstall

notifications:
  email:
    - sebastian.jedruszkiewicz@blstream.com
