language: objective-c
rvm: 1.9.3
branches:
  only:
    - master
before_script:
- sudo easy_install cpp-coveralls
- sudo easy_install PyYAML
- brew update
- brew upgrade xctool
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/MyHoard_AdHoc_Distribution.mobileprovision.enc -d -a -out scripts/profile/MyHoard_AdHoc_Distribution.mobileprovision
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
- openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
- ./scripts/add-key.sh
script:
- xctool -workspace MyHoard.xcworkspace -scheme MyHoard -sdk iphoneos -configuration Release OBJROOT="$PWD/build" SYMROOT="$PWD/build" ONLY_ACTIVE_ARCH=NO
- xctool test -workspace MyHoard.xcworkspace -scheme MyHoardTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -configuration Debug
after_script:
- ./scripts/remove-key.sh
after_success:
- ./scripts/coveralls.sh
- ./scripts/sign-and-upload.sh
notifications:
  email:
  - sebastian.jedruszkiewicz@blstream.com
  - karol.kogut@blstream.com
env:
  global:
  - secure: dpoYPkSt1AybS7nIAek7+N8HcmBPOKzrBW26EiopfC6DIt8AqnkO3pk1rkrs3+chP298Ah9oytOVk0LgtnId/DYgIEdWHX1jbLMQnXKHBefDJXvd63vzUj2LAKVmXo4RE0diHPtwFIoi7V8m+YTNgFrJtTK1UqyurhhTWrRRDrU=
  - APP_NAME="MyHoard"
  - 'DEVELOPER_NAME="iPhone Distribution: BLStream (XTRY58ZV6V)"'
  - PROFILE_NAME="MyHoard_AdHoc_Distribution"
  - secure: U8VugqPamlZ2ybSzDwWDV1Aq9RxsAWn5v1MyYe5qsLRguDw34iHDdyhiGeqld9R/unkTsheSPP8eI0RDOn383rgr35MKp6M9WbYfN6rBW8cBhIKbkOBHH7oM+0sWhXlg46rMMbG+85BaP8VmIMNEl6LfhMUSm4K2+IMZxblHAmc=
  - secure: MxhPhWn3gD3tdLAwJGvcg/sGDxm43HHTw7Dqti7+MMotW64RKbwTmg8kyXXNNqK8buDhhoVJ7qDCgOEC7MqxRWq1Ud96vsl2MsvDKOh0hSKWgbXVdAuATYZhKGhfRRoqgS1D7tNhBA+nEXF+2n5oyO9t5/OiIEXb87cWmm6TUlM=
  - secure: G0PhUvlXqKEKA0q8XzVzdbaXMQKcvnd3dcHOQQvCeuq/26VkOW9khm9yxg60xseKzlkuWaJHH4nIDg9qGml/I6RbzQ7ranoeJ3iaH9yi+UjvF9tGilWSRne61uvwZ8xzSNd0CngviLSl6wF/AptZXET5g+vbbit1e2pj24bCdbE=
  - secure: P/9/fxmgvHd04lN81hYgC8R13EvM1yEgSauySqc9QfQRCeyQD+g2K/eM5ZYg2ucIA8/7/YFdlk8xEaYfgUhufYve0a4UPoFK6lnKhpMJPXnf7w9nnKmrDiW/jdFNby1TZosCL+uMFJxXQSOFbeOX5sPeU5TQNvjiaijsT/LHSlo=
