language: objective-c

rvm: 1.9.3

before_script:
  - brew update
  - brew upgrade xctool

script:
  - xctool -workspace MyHoard.xcworkspace -scheme MyHoard -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool test -workspace MyHoard.xcworkspace -scheme MyHoardTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

notifications:
  email:
    - sebastian.jedruszkiewicz@blstream.com
    - karol.kogut@blstream.com
